[package]
name = "rustls-cng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.20"
wincms = { git = "https://github.com/ancwrd1/wincms.git" }
anyhow = "1"
sha2 = "0.10"
