[package]
name = "rustls-cng"
version = "0.1.1"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "Windows CNG API bridge for rustls"
license = "MIT/Apache-2.0"
repository = "https://github.com/ancwrd1/rustls-cng"
documentation = "https://docs.rs/rustls-cng"
readme = "README.md"
keywords = ["cng", "tls", "rustls", "windows"]
edition = "2021"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-gnu"

[dependencies]
rustls = "0.20"
sha2 = "0.10"
windows = { version = "0.37", features = [
    "alloc", "Win32_Foundation", "Win32_Security_Cryptography"] }
widestring = "1.0.0-beta.1"
thiserror = "1"

[dev-dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
