[package]
name = "rustls-cng"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = "0.20"
sha2 = "0.10"
windows = { version = "0.37", features = [
    "alloc", "Win32_Foundation", "Win32_Security_Cryptography"] }
widestring = "1.0.0-beta.1"
thiserror = "1"
